"""create vehicles table

Revision ID: 0457d004d142
Revises: 7932e6a48abc
Create Date: 2026-03-31 20:00:20.759078

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0457d004d142"
down_revision = "7932e6a48abc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("license_plate", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=20), nullable=False),
        sa.Column("brand", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("license_plate"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicles")
    # ### end Alembic commands ###
