"""create lessons table

Revision ID: 1a42a95e3c1d
Revises: 9bf554c84c6b
Create Date: 2026-04-08 23:03:51.454979

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1a42a95e3c1d"
down_revision = "9bf554c84c6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("lesson_number", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=100), nullable=True),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("instructor_vehicle_id", sa.Integer(), nullable=False),
        sa.Column("lesson_type", sa.Integer(), nullable=False),
        sa.Column("lesson_status", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["enrollments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor_vehicle_id"],
            ["instructor_vehicles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lesson_status"],
            ["lesson_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lesson_type"],
            ["lesson_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lessons")
    # ### end Alembic commands ###
