"""db: add lesson_status_id and lesson_type_id to lessons

Revision ID: 256ad1e195de
Revises: 810df4b5caed
Create Date: 2026-04-10 15:48:21.847454

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "256ad1e195de"
down_revision = "810df4b5caed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.add_column(sa.Column("lesson_type_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("lesson_status_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f("lessons_ibfk_3"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("lessons_ibfk_4"), type_="foreignkey")
        batch_op.create_foreign_key(None, "lesson_types", ["lesson_type_id"], ["id"])
        batch_op.create_foreign_key(
            None, "lesson_statuses", ["lesson_status_id"], ["id"]
        )
        batch_op.drop_column("lesson_type")
        batch_op.drop_column("lesson_status")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lessons", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "lesson_status",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "lesson_type",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("lessons_ibfk_4"), "lesson_types", ["lesson_type"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("lessons_ibfk_3"), "lesson_statuses", ["lesson_status"], ["id"]
        )
        batch_op.drop_column("lesson_status_id")
        batch_op.drop_column("lesson_type_id")

    # ### end Alembic commands ###
