"""feat(db): add is_default field to lesson_statuses and lesson_types

Revision ID: 2bcf7712feaa
Revises: 256ad1e195de
Create Date: 2026-04-12 17:37:06.017500

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bcf7712feaa"
down_revision = "256ad1e195de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_default", sa.Boolean(), nullable=True))

    with op.batch_alter_table("lesson_types", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_default", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_types", schema=None) as batch_op:
        batch_op.drop_column("is_default")

    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.drop_column("is_default")

    # ### end Alembic commands ###
