"""db: add show_in_scheduling in lesson statuses

Revision ID: 314cef73ba09
Revises: 2bcf7712feaa
Create Date: 2026-04-29 12:46:25.000052

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "314cef73ba09"
down_revision = "2bcf7712feaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("show_in_scheduling", sa.Boolean(), nullable=True)
        )
        batch_op.alter_column(
            "show_in_schedule",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.alter_column(
            "show_in_schedule",
            existing_type=mysql.TINYINT(display_width=1),
            nullable=False,
        )
        batch_op.drop_column("show_in_scheduling")

    # ### end Alembic commands ###
