"""create instructors table

Revision ID: 4350f67b10fd
Revises: 7811ceba9696
Create Date: 2026-03-06 15:55:49.826727

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4350f67b10fd"
down_revision = "7811ceba9696"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instructors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("contract", sa.String(length=50), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("instructors")
    # ### end Alembic commands ###
