"""drop show_in_schedule of lesson statuses

Revision ID: 66cb58fafe38
Revises: 314cef73ba09
Create Date: 2026-04-29 22:11:07.913319

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "66cb58fafe38"
down_revision = "314cef73ba09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.drop_column("show_in_schedule")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "show_in_schedule",
                mysql.TINYINT(display_width=1),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
