"""add unique constraint to blocked_days

Revision ID: 722abfb68552
Revises: 1ee88e7c2156
Create Date: 2026-06-26 15:47:39.929481

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "722abfb68552"
down_revision = "1ee88e7c2156"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blocked_days", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "ux_blocked_days_date_instructor", ["date", "instructor_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blocked_days", schema=None) as batch_op:
        batch_op.drop_constraint("ux_blocked_days_date_instructor", type_="unique")

    # ### end Alembic commands ###
