"""db: add show_in_schedule to lesson_statuses

Revision ID: 810df4b5caed
Revises: 1a42a95e3c1d
Create Date: 2026-04-10 15:29:34.869843

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "810df4b5caed"
down_revision = "1a42a95e3c1d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("show_in_schedule", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_statuses", schema=None) as batch_op:
        batch_op.drop_column("show_in_schedule")

    # ### end Alembic commands ###
